<?php

/**
 * This is commercial software, only users who have purchased a valid license
 * and accept to the terms of the License Agreement can install and use this
 * program.
 *
 * Do not edit or add to this file if you wish to upgrade Godomall5 to newer
 * versions in the future.
 *
 * @copyright ¨Ï 2016, NHN godo: Corp.
 * @link      http://www.godo.co.kr
 */
namespace Controller\Mobile\Mypage;


class MyPageController extends \Bundle\Controller\Mobile\Mypage\MyPageController
{
    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
        if ( \Request::getRemoteAddress() === '182.216.219.157' || \Request::getRemoteAddress() === '112.146.205.124' || \Request::getRemoteAddress() === '121.141.26.133' || \Request::getRemoteAddress() === '121.141.26.134' || \Request::getRemoteAddress() === '121.167.104.240') {
            $this->setData('test',0);
        } else {
            $this->setData('test',1);
        }

    }
}